export const loginStyles = {
  width: "100%",
  height: "100%",
  display: "flex",
  justifyContent: "center",
  alignItems: "center",
  marginBlock: "auto",
  form: {
    display: "flex",
    width: "400px",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "transparent",
    padding: "40px",
    borderRadius: "10px",
    boxShadow: "0 0 10px 10px rgba(0, 0, 0, 0.1)",
    zIndex: "1",
    color: "#fff",
    gap: "40px",
    backdropFilter: "blur(10px)",
    inputsBox: {
      width: "100%",
      display: "flex",
      flexDirection: "column",
      justifyContent: "center",
      rowGap: "30px",
      field: {
        display: "flex",
        flexDirection: "column",
        width: "100%",
        alignItems: "center",
        label: {
          alignSelf: "start",
          marginBottom: "5px",
        },
        input: {
        width: "100%",
        height: "30px",
        backgroundColor: "rgb(21 23 28)",
        borderRadius: "5px",
        border: "none",
        outline: "2px solid #61dafb",
        color: "#fff",
        padding: "10px",
        },
      },
    },
  },
};