export const productsStyles = {
  width: '100%',
  height: '100%',
  display: 'flex',
  justifyContent: 'flex-start',
  alignItems: 'center',
  flexDirection: 'column',
  paddingBlock: '10px',
  backgroundColor: 'transparent',
  rowGap: '20px',
  color: '#fff',
  zIndex: 1,
  search: {
    width: '100%',
    height: '30px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    columnGap: '5px',
    input: {
      width: '30%',
      height: '100%',
      borderRadius: '5px',
      border: 'none',
      outline: 'none',
      padding: '5px 10px',
      backgroundColor: '#333a45',
    },
    searchBtn: {
      width: 'fit-content',
      height: '100%',
      borderRadius: '5px',
      border: 'none',
      outline: 'none',
      padding: '5px 10px',
      backgroundColor: 'rgb(97, 218, 251)',
      cursor: 'pointer',
      color: '#fff',
    },
  },
  nav: {
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    columnGap: '5px',
    link: {
      width: 'fit-content',
      height: '100%',
      borderRadius: '5px',
      border: 'none',
      outline: 'none',
      padding: '5px 10px',
      backgroundColor: '#61dafb',
      cursor: 'pointer',
    },
  },
};